---
title:  'História do R'
subtitle: |
  Conheça um pouco mais sobre como tudo começou!
authors: 
- Silvio
date: "2019-04-26 00:00:00"
categories: ["Curiosidades"]
tags: [história, R, Silvio, estatística,  language S]
output: md_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Imagine o seguinte cenário: você é um professor que utiliza vários softwares em suas aulas e, como professor, sua missão é a de ensinar a cada um de seus alunos como usar todos eles. 
Além disso, ainda há outro problema! Os softwares disponíveis no mercado são de alto custo e, portanto, a maioria dos alunos dificilmente terá acesso à essas ferramentas após concluírem o curso. 

A questão é: Como lidar com tais softwares dada as dificuldades financeiras dos estudantes ao deixarem a universidade? De quais softwares comprar as permissões e licenças?

Bom, essa era a motivação de Ross Ihaka e Robert Gentleman. Dois professores da Universidade de Auckland (Nova Zelândia) que se depararam com esse cenário incômodo.  Coincidência ou não, em 1993 Ross teve acesso a um livro chamado "*New S language*”, que lhe trouxe uma ideia inusitada. Tomando como base as ideias da linguagem S, os dois professores produziram sua própria linguagem de computador para dar aulas sobre estatística, e deram à ela o nome de R (que faz menção ao nome de seus criadores e também faz referencia à linguagem S que originou o R).

No início, o R era apenas distribuído entre os alunos que, após as aulas levavam cópias do recém criado software para casa. Contudo, essas cópias foram sendo repassadas entre os alunos e dos alunos para a comunidade, aumentando o interesse de diversos usuários sobre a linguagem. Até que, em julho de 1995, Ross e Robert começaram a disseminar o software R publicamente, já que uma nova linguagem de programação surgira, disponibilizando-a no  servidor da universidade. O sucesso do R foi tanto, que após 2 anos a linguagem já tinha visibilidade mundial e despertou o interesse de muitos desenvolvedores, inclusive John Chambers, um dos idealizadores e criadores da linguagem S.

Nos últimos anos o R se tornou o queridinho de muitas empresas, especialmente das gigantes do ramo da tecnologia, como Facebook e Google, atraídas pelas vantagens do R sobre outros softwares, como  custo, rápidez e código aberto, além das excelentes funcionalidades para análises estatísticas. Curiosamente hoje, a linguagem está no top 3 das linguagens mais utilizadas por cientistas de dados e, certamente, é uma das mais utilizadas entre os estudantes da estatística, engenharia, economia, epidemiologia, medicina e àreas afins.

Silvio Cabral.

> Referências:

1. Fox, John. 2009 Aspects of the Social Organization and Trajectory of the R Project. R Journal.
2. Ihaka, Ross e Gentleman, Robert. 1996 R: A language for data analysis and graphics. Journal of Computational and Graphical Statistics.
